In [150]:
import pandas as pd

In [151]:
df = pd.read_csv("../data_dumps/products_website.csv", sep=",")
df.head()
len(df)

7298

In [152]:
column_names = df.columns.tolist()
column_names, len(column_names)

(['Handle',
  'Title',
  'Body (HTML)',
  'Vendor',
  'Product Category',
  'Type',
  'Tags',
  'Published',
  'Option1 Name',
  'Option1 Value',
  'Option1 Linked To',
  'Option2 Name',
  'Option2 Value',
  'Option2 Linked To',
  'Option3 Name',
  'Option3 Value',
  'Option3 Linked To',
  'Variant SKU',
  'Variant Grams',
  'Variant Inventory Tracker',
  'Variant Inventory Policy',
  'Variant Fulfillment Service',
  'Variant Price',
  'Variant Compare At Price',
  'Variant Requires Shipping',
  'Variant Taxable',
  'Unit Price Total Measure',
  'Unit Price Total Measure Unit',
  'Unit Price Base Measure',
  'Unit Price Base Measure Unit',
  'Variant Barcode',
  'Image Src',
  'Image Position',
  'Image Alt Text',
  'Gift Card',
  'SEO Title',
  'SEO Description',
  'code (product.metafields.custom.code)',
  'discount_value (product.metafields.custom.discount_value)',
  'gender (product.metafields.custom.gender)',
  'gender_list (product.metafields.custom.gender_list)',
  'type1 (product.metafields.custom.type1)',
  'type2 (product.metafields.custom.type2)',
  'type3 (product.metafields.custom.type3)',
  'with_images (product.metafields.custom.with_images)',
  'Complementary products (product.metafields.shopify--discovery--product_recommendation.complementary_products)',
  'Related products (product.metafields.shopify--discovery--product_recommendation.related_products)',
  'Related products settings (product.metafields.shopify--discovery--product_recommendation.related_products_display)',
  'Search product boosts (product.metafields.shopify--discovery--product_search_boost.queries)',
  'Variant Image',
  'Variant Weight Unit',
  'Variant Tax Code',
  'Cost per item',
  'Status'],
 54)

In [153]:
(df.notnull().mean() * 100).round(2)

Handle                                                                                                                100.00
Title                                                                                                                  19.05
Body (HTML)                                                                                                             0.00
Vendor                                                                                                                 19.05
Product Category                                                                                                        0.03
Type                                                                                                                    0.00
Tags                                                                                                                   19.05
Published                                                                                                              19.05
Option1 Name                                                                                                           19.05
Option1 Value                                                                                                          52.51
Option1 Linked To                                                                                                       0.00
Option2 Name                                                                                                           19.05
Option2 Value                                                                                                          52.51
Option2 Linked To                                                                                                       0.00
Option3 Name                                                                                                            0.00
Option3 Value                                                                                                           0.00
Option3 Linked To                                                                                                       0.00
Variant SKU                                                                                                            52.51
Variant Grams                                                                                                          52.51
Variant Inventory Tracker                                                                                              52.51
Variant Inventory Policy                                                                                               52.51
Variant Fulfillment Service                                                                                            52.51
Variant Price                                                                                                          52.51
Variant Compare At Price                                                                                               49.27
Variant Requires Shipping                                                                                              52.51
Variant Taxable                                                                                                        52.51
Unit Price Total Measure                                                                                                0.00
Unit Price Total Measure Unit                                                                                           0.00
Unit Price Base Measure                                                                                                 0.00
Unit Price Base Measure Unit                                                                                            0.00
Variant Barcode                                                                                                        52.51
Image Src                                                                                                              90.08
Image Position                                                                                                         90.08
Image Alt Text                                                                                                         90.08
Gift Card                                                                                                              19.05
SEO Title                                                                                                               0.00
SEO Description                                                                                                         0.00
code (product.metafields.custom.code)                                                                                  19.05
discount_value (product.metafields.custom.discount_value)                                                               2.00
gender (product.metafields.custom.gender)                                                                               0.00
gender_list (product.metafields.custom.gender_list)                                                                    19.05
type1 (product.metafields.custom.type1)                                                                                18.44
type2 (product.metafields.custom.type2)                                                                                19.05
type3 (product.metafields.custom.type3)                                                                                19.05
with_images (product.metafields.custom.with_images)                                                                    15.06
Complementary products (product.metafields.shopify--discovery--product_recommendation.complementary_products)           0.00
Related products (product.metafields.shopify--discovery--product_recommendation.related_products)                       0.00
Related products settings (product.metafields.shopify--discovery--product_recommendation.related_products_display)      0.00
Search product boosts (product.metafields.shopify--discovery--product_search_boost.queries)                             0.00
Variant Image                                                                                                           0.00
Variant Weight Unit                                                                                                    52.51
Variant Tax Code                                                                                                        0.00
Cost per item                                                                                                           0.00
Status                                                                                                                 19.05
dtype: float64

In [154]:
df = df.loc[:, df.notna().mean() >= 0.1]
(df.notnull().mean() * 100).round(2)

Handle                                                 100.00
Title                                                   19.05
Vendor                                                  19.05
Tags                                                    19.05
Published                                               19.05
Option1 Name                                            19.05
Option1 Value                                           52.51
Option2 Name                                            19.05
Option2 Value                                           52.51
Variant SKU                                             52.51
Variant Grams                                           52.51
Variant Inventory Tracker                               52.51
Variant Inventory Policy                                52.51
Variant Fulfillment Service                             52.51
Variant Price                                           52.51
Variant Compare At Price                                49.27
Variant Requires Shipping                               52.51
Variant Taxable                                         52.51
Variant Barcode                                         52.51
Image Src                                               90.08
Image Position                                          90.08
Image Alt Text                                          90.08
Gift Card                                               19.05
code (product.metafields.custom.code)                   19.05
gender_list (product.metafields.custom.gender_list)     19.05
type1 (product.metafields.custom.type1)                 18.44
type2 (product.metafields.custom.type2)                 19.05
type3 (product.metafields.custom.type3)                 19.05
with_images (product.metafields.custom.with_images)     15.06
Variant Weight Unit                                     52.51
Status                                                  19.05
dtype: float64

In [155]:
df.head(5)

,Handle,Title,Vendor,Tags,Published,Option1 Name,Option1 Value,Option2 Name,Option2 Value,Variant SKU,...,Image Alt Text,Gift Card,code (product.metafields.custom.code),gender_list (product.metafields.custom.gender_list),type1 (product.metafields.custom.type1),type2 (product.metafields.custom.type2),type3 (product.metafields.custom.type3),with_images (product.metafields.custom.with_images),Variant Weight Unit,Status
0,tshirt-wardrums-tshirt-wardrums-white-ss-25,Tshirt WARDRUMS,DEVA STATES,with_images,False,size,L,color,WHITE,TSHIRT-WARDRUMS-WHITE-SS-25-L-WHITE-2700009550619,...,Product image by Kixbox,False,TSHIRT_WARDRUMS-WHITE-SS-25,Mens,T-shirt Short Sleeve,T-shirt,Light Knitwear,True,kg,draft
1,tshirt-wardrums-tshirt-wardrums-white-ss-25,NaN,NaN,NaN,NaN,NaN,M,NaN,WHITE,TSHIRT-WARDRUMS-WHITE-SS-25-M-WHITE-2700009550602,...,Product image by Kixbox,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kg,NaN
2,tshirt-wardrums-tshirt-wardrums-white-ss-25,NaN,NaN,NaN,NaN,NaN,XL,NaN,WHITE,TSHIRT-WARDRUMS-WHITE-SS-25-XL-WHITE-270000955...,...,Product image by Kixbox,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kg,NaN
3,tshirt-wardrums-tshirt-wardrums-white-ss-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Product image by Kixbox,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,tshirt-wardrums-tshirt-wardrums-white-ss-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Product image by Kixbox,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [156]:
df.nunique()

Handle                                                 1390
Title                                                   945
Vendor                                                   28
Tags                                                      2
Published                                                 2
Option1 Name                                              2
Option1 Value                                           244
Option2 Name                                              2
Option2 Value                                           373
Variant SKU                                            3832
Variant Grams                                             1
Variant Inventory Tracker                                 1
Variant Inventory Policy                                  1
Variant Fulfillment Service                               1
Variant Price                                           138
Variant Compare At Price                                 99
Variant Requires Shipping                                 1
Variant Taxable                                           1
Variant Barcode                                        3832
Image Src                                              6574
Image Position                                           22
Image Alt Text                                            1
Gift Card                                                 1
code (product.metafields.custom.code)                  1390
gender_list (product.metafields.custom.gender_list)       3
type1 (product.metafields.custom.type1)                 124
type2 (product.metafields.custom.type2)                  27
type3 (product.metafields.custom.type3)                   9
with_images (product.metafields.custom.with_images)       1
Variant Weight Unit                                       1
Status                                                    2
dtype: int64

In [157]:
df.duplicated().sum()

np.int64(0)

In [158]:
df = df[df.notna().sum(axis=1) >= 5]
print(len(df))
df.head()

3832

,Handle,Title,Vendor,Tags,Published,Option1 Name,Option1 Value,Option2 Name,Option2 Value,Variant SKU,...,Image Alt Text,Gift Card,code (product.metafields.custom.code),gender_list (product.metafields.custom.gender_list),type1 (product.metafields.custom.type1),type2 (product.metafields.custom.type2),type3 (product.metafields.custom.type3),with_images (product.metafields.custom.with_images),Variant Weight Unit,Status
0,tshirt-wardrums-tshirt-wardrums-white-ss-25,Tshirt WARDRUMS,DEVA STATES,with_images,False,size,L,color,WHITE,TSHIRT-WARDRUMS-WHITE-SS-25-L-WHITE-2700009550619,...,Product image by Kixbox,False,TSHIRT_WARDRUMS-WHITE-SS-25,Mens,T-shirt Short Sleeve,T-shirt,Light Knitwear,True,kg,draft
1,tshirt-wardrums-tshirt-wardrums-white-ss-25,NaN,NaN,NaN,NaN,NaN,M,NaN,WHITE,TSHIRT-WARDRUMS-WHITE-SS-25-M-WHITE-2700009550602,...,Product image by Kixbox,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kg,NaN
2,tshirt-wardrums-tshirt-wardrums-white-ss-25,NaN,NaN,NaN,NaN,NaN,XL,NaN,WHITE,TSHIRT-WARDRUMS-WHITE-SS-25-XL-WHITE-270000955...,...,Product image by Kixbox,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kg,NaN
6,zipper-wallet-zipwallet01-natural-leather-aw-25,ZIPPER WALLET,MISTER GREEN,with_images,False,color,NATURAL LEATHER,size,ONE SIZE,ZIPWALLET01-NATURAL-LEATHER-AW-25-ONE-SIZE-NAT...,...,Product image by Kixbox,False,ZIPWALLET01-NATURAL LEATHER-AW-25,Mens\nWomens,Zippered Leather Wallet,Wallets,Accessories,True,kg,draft
9,zipper-wallet-zipwallet01-green-leather-aw-25,ZIPPER WALLET,MISTER GREEN,with_images,False,color,GREEN LEATHER,size,ONE SIZE,ZIPWALLET01-GREEN-LEATHER-AW-25-ONE-SIZE-GREEN...,...,Product image by Kixbox,False,ZIPWALLET01-GREEN LEATHER-AW-25,Mens\nWomens,Zippered Leather Wallet,Wallets,Accessories,True,kg,draft

In [159]:
(df.notnull().mean() * 100).round(2)

Handle                                                 100.00
Title                                                   36.27
Vendor                                                  36.27
Tags                                                    36.27
Published                                               36.27
Option1 Name                                            36.27
Option1 Value                                          100.00
Option2 Name                                            36.27
Option2 Value                                          100.00
Variant SKU                                            100.00
Variant Grams                                          100.00
Variant Inventory Tracker                              100.00
Variant Inventory Policy                               100.00
Variant Fulfillment Service                            100.00
Variant Price                                          100.00
Variant Compare At Price                                93.84
Variant Requires Shipping                              100.00
Variant Taxable                                        100.00
Variant Barcode                                        100.00
Image Src                                               81.11
Image Position                                          81.11
Image Alt Text                                          81.11
Gift Card                                               36.27
code (product.metafields.custom.code)                   36.27
gender_list (product.metafields.custom.gender_list)     36.27
type1 (product.metafields.custom.type1)                 35.13
type2 (product.metafields.custom.type2)                 36.27
type3 (product.metafields.custom.type3)                 36.27
with_images (product.metafields.custom.with_images)     28.68
Variant Weight Unit                                    100.00
Status                                                  36.27
dtype: float64

In [160]:
cols = [
    'Title', 'Vendor', 'Tags', 'Published',
    'Option1 Name', 'Option2 Name',
    'Gift Card',
    'code (product.metafields.custom.code)',
    'gender_list (product.metafields.custom.gender_list)',
    'type1 (product.metafields.custom.type1)',
    'type2 (product.metafields.custom.type2)',
    'type3 (product.metafields.custom.type3)',
    'Status'
]
filled_counts = df[cols].notna().sum(axis=1)
filled_counts.value_counts()

0     2442
13    1346
12      44
Name: count, dtype: int64

0 - вообще ни одна не заполнена
13 - заполнены все колонки
12 - заполнены почти все колонки
По этим колонкам, либо заполнено все, либо не заполнено ничего

In [161]:
all_or_nothing = (filled_counts == 0) | (filled_counts == len(cols))

all_or_nothing.value_counts()

True     3788
False      44
Name: count, dtype: int64

In [162]:
df = df[df[cols].notna().sum(axis=1) > 0]
df.head()

,Handle,Title,Vendor,Tags,Published,Option1 Name,Option1 Value,Option2 Name,Option2 Value,Variant SKU,...,Image Alt Text,Gift Card,code (product.metafields.custom.code),gender_list (product.metafields.custom.gender_list),type1 (product.metafields.custom.type1),type2 (product.metafields.custom.type2),type3 (product.metafields.custom.type3),with_images (product.metafields.custom.with_images),Variant Weight Unit,Status
0,tshirt-wardrums-tshirt-wardrums-white-ss-25,Tshirt WARDRUMS,DEVA STATES,with_images,False,size,L,color,WHITE,TSHIRT-WARDRUMS-WHITE-SS-25-L-WHITE-2700009550619,...,Product image by Kixbox,False,TSHIRT_WARDRUMS-WHITE-SS-25,Mens,T-shirt Short Sleeve,T-shirt,Light Knitwear,True,kg,draft
6,zipper-wallet-zipwallet01-natural-leather-aw-25,ZIPPER WALLET,MISTER GREEN,with_images,False,color,NATURAL LEATHER,size,ONE SIZE,ZIPWALLET01-NATURAL-LEATHER-AW-25-ONE-SIZE-NAT...,...,Product image by Kixbox,False,ZIPWALLET01-NATURAL LEATHER-AW-25,Mens\nWomens,Zippered Leather Wallet,Wallets,Accessories,True,kg,draft
9,zipper-wallet-zipwallet01-green-leather-aw-25,ZIPPER WALLET,MISTER GREEN,with_images,False,color,GREEN LEATHER,size,ONE SIZE,ZIPWALLET01-GREEN-LEATHER-AW-25-ONE-SIZE-GREEN...,...,Product image by Kixbox,False,ZIPWALLET01-GREEN LEATHER-AW-25,Mens\nWomens,Zippered Leather Wallet,Wallets,Accessories,True,kg,draft
12,wordmark-hemp-underwear-2-pack-underwear-chlor...,Wordmark Hemp Underwear - 2 Pack,MISTER GREEN,with_images,False,size,L,color,CHLOROPHYLL/NAVY,UNDERWEAR-CHLOROPHYLL-NAVY-AW-25-L-CHLOROPHYLL...,...,Product image by Kixbox,False,UNDERWEAR-CHLOROPHYLL/NAVY-AW-25,Mens,NaN,Other,Accessories,True,kg,draft
17,collection-15-tool-bag-set-toolbagset-chartreu...,COLLECTION 15 TOOL BAG SET,MISTER GREEN,with_images,False,size,ONE SIZE,color,CHARTREUSE / RED / BLACK,TOOLBAGSET-CHARTREUSE-RED-BLACK-AW-25-ONE-SIZE...,...,Product image by Kixbox,False,TOOLBAGSET-CHARTREUSE / RED / BLACK-AW-25,Mens\nWomens,NaN,Other,Accessories,True,kg,draft

In [163]:
(df.notnull().mean() * 100).round(2)

Handle                                                 100.00
Title                                                  100.00
Vendor                                                 100.00
Tags                                                   100.00
Published                                              100.00
Option1 Name                                           100.00
Option1 Value                                          100.00
Option2 Name                                           100.00
Option2 Value                                          100.00
Variant SKU                                            100.00
Variant Grams                                          100.00
Variant Inventory Tracker                              100.00
Variant Inventory Policy                               100.00
Variant Fulfillment Service                            100.00
Variant Price                                          100.00
Variant Compare At Price                                95.25
Variant Requires Shipping                              100.00
Variant Taxable                                        100.00
Variant Barcode                                        100.00
Image Src                                               79.06
Image Position                                          79.06
Image Alt Text                                          79.06
Gift Card                                              100.00
code (product.metafields.custom.code)                  100.00
gender_list (product.metafields.custom.gender_list)    100.00
type1 (product.metafields.custom.type1)                 96.83
type2 (product.metafields.custom.type2)                100.00
type3 (product.metafields.custom.type3)                100.00
with_images (product.metafields.custom.with_images)     79.06
Variant Weight Unit                                    100.00
Status                                                 100.00
dtype: float64

In [164]:
df.nunique(dropna=False)

Handle                                                 1390
Title                                                   945
Vendor                                                   28
Tags                                                      2
Published                                                 2
Option1 Name                                              2
Option1 Value                                           230
Option2 Name                                              2
Option2 Value                                           365
Variant SKU                                            1390
Variant Grams                                             1
Variant Inventory Tracker                                 1
Variant Inventory Policy                                  1
Variant Fulfillment Service                               1
Variant Price                                           136
Variant Compare At Price                                 99
Variant Requires Shipping                                 1
Variant Taxable                                           1
Variant Barcode                                        1390
Image Src                                              1100
Image Position                                            2
Image Alt Text                                            2
Gift Card                                                 1
code (product.metafields.custom.code)                  1390
gender_list (product.metafields.custom.gender_list)       3
type1 (product.metafields.custom.type1)                 125
type2 (product.metafields.custom.type2)                  27
type3 (product.metafields.custom.type3)                   9
with_images (product.metafields.custom.with_images)       2
Variant Weight Unit                                       1
Status                                                    2
dtype: int64

In [165]:
cols_to_drop = df.columns[df.nunique(dropna=False) <= 1]
cols_to_drop

Index(['Variant Grams', 'Variant Inventory Tracker',
       'Variant Inventory Policy', 'Variant Fulfillment Service',
       'Variant Requires Shipping', 'Variant Taxable', 'Gift Card',
       'Variant Weight Unit'],
      dtype='str')

In [166]:
df = df.loc[:, df.nunique(dropna=False) > 1]

In [170]:
for element in df.columns.to_list():
	print(element)

Handle
Title
Vendor
Tags
Published
Option1 Name
Option1 Value
Option2 Name
Option2 Value
Variant SKU
Variant Price
Variant Compare At Price
Variant Barcode
Image Src
Image Position
Image Alt Text
code (product.metafields.custom.code)
gender_list (product.metafields.custom.gender_list)
type1 (product.metafields.custom.type1)
type2 (product.metafields.custom.type2)
type3 (product.metafields.custom.type3)
with_images (product.metafields.custom.with_images)
Status

In [168]:
df.to_csv('../cleaned_data/products_website.csv')

In [171]:
len(df), len(df.columns)

(1390, 23)